services:
  ollama-container:
    build:
      context: .
      dockerfile: ./Containerfile.ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    volumes:
        - ./ollama/ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
        - ./.env:/root/.env
    env_file:
      - .env
    networks:
      - ollama-network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]  
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
  
  chroma-db:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    networks:
      - ollama-network 
    env_file:
     - .env
    volumes:
      - ./local_rag_chatbot/assets/db/chroma.sqlite3:/data/chroma.sqlite3:Z

  streamlit-app:
    build:
      context: .
      dockerfile: ./Containerfile.streamlit
    container_name: streamlit-app
    environment:
      BASE_URL: http://ollama-container:11434
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - ollama-network 
    depends_on:
      ollama-container:
        condition: service_healthy
      # chroma-db:
      #   condition: service_healthy

networks:
  ollama-network:
    driver: bridge 